name: ğŸš€ğŸ§¨ Destroy Infrastructure with Terraform 

on:
  issues: 
    types: closed

defaults:
  run:
    working-directory: ./terraform

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.TF_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.TF_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.TF_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.TF_TENANT_ID }}


jobs:
  destroy_terraform_infra:

    name: "BOOM! ğŸ’¥"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code ğŸ›
        uses: actions/checkout@v4

      - name: Set up Terraform ğŸ’¼
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init ğŸ—
        id: init
        run: | 
          terraform init \
          -backend-config="resource_group_name=${{ secrets.TF_STATE_RESOURCE_GROUP_NAME }}" \
          -backend-config="storage_account_name=${{ secrets.TF_STATE_AZURE_STORAGE_NAME }}" \
          -backend-config="container_name=${{ secrets.TF_STATE_CONTAINER_NAME }}" \
          -backend-config="key=issue-${{ github.event.issue.number }}-terraform.tfstate" \
          -backend-config="access_key=${{ secrets.TF_STATE_STORAGE_ACCESS_KEY }}"


      - name: Create a terraform.tfvars file
        run:  | 
          echo location="$(terraform output location)" >> terraform.tfvars
          echo resource_group_name="$(terraform output resource_group_name)" >> terraform.tfvars
          echo storage_account_name="$(terraform output storage_account_name)" >> terraform.tfvars
          echo subscription_id="${{ secrets.TF_SUBSCRIPTION_ID }}" >> terraform.tfvars

          cat terraform.tfvars

          # terraform fmt
          
      - name: Check the content of the terraform.tfvars file
        run: cat terraform.tfvars

      - name: Terraform Destroy ğŸ§¨
        run: terraform destroy -auto-approve

      - name: Remove Labels
        id: remove-labels
        uses: issue-ops/labeler@v2.1.0
        with:
          action: remove
          issue_number: ${{ github.event.issue.number }}
          labels: |
            deployed ğŸš€âœ…        

      - name: Add Labels
        id: add-labels
        uses: issue-ops/labeler@v2.1.0
        with:
          action: add
          issue_number: ${{ github.event.issue.number }}
          labels: |
            destroyed ğŸš€ğŸ”¥
